spring:
  main:
    show_banner: false
  data:
    rest:
      launchJobs: /launchSearchQueriesJob
      neighbours: /wordNeighbours
      words: /words
  hadoop:
    masterNodeIp: localhost
    port: 9000
    fsUri: hdfs://${spring.hadoop.masterNodeIp}:${spring.hadoop.port}
    mapReduceInput: /user/root/input
hbase:
  zk:
    host: ${spring.hadoop.masterNodeIp}
    port: 2181
  mapred:
    occurrencesTable: word
    neighboursTable: neighbours